// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdEV_84_i04B8pnyIA5blmAtxDwxWQ24Y',
    appId: '1:496597139466:web:e4a7c4b28ab13784a6dff3',
    messagingSenderId: '496597139466',
    projectId: 'slack-clone-120c3',
    authDomain: 'slack-clone-120c3.firebaseapp.com',
    storageBucket: 'slack-clone-120c3.firebasestorage.app',
    measurementId: 'G-2X5R9V8FN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIVPHCIkNV1KjY-N8YHZ_wgzFBsWAF4d4',
    appId: '1:496597139466:android:32a1f939423870aaa6dff3',
    messagingSenderId: '496597139466',
    projectId: 'slack-clone-120c3',
    storageBucket: 'slack-clone-120c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKbyd0Qaq63WhFrg_l_CbBVKyGPF2Wt0U',
    appId: '1:496597139466:ios:712ceed306735a8ea6dff3',
    messagingSenderId: '496597139466',
    projectId: 'slack-clone-120c3',
    storageBucket: 'slack-clone-120c3.firebasestorage.app',
    iosBundleId: 'com.example.slackClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKbyd0Qaq63WhFrg_l_CbBVKyGPF2Wt0U',
    appId: '1:496597139466:ios:712ceed306735a8ea6dff3',
    messagingSenderId: '496597139466',
    projectId: 'slack-clone-120c3',
    storageBucket: 'slack-clone-120c3.firebasestorage.app',
    iosBundleId: 'com.example.slackClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdEV_84_i04B8pnyIA5blmAtxDwxWQ24Y',
    appId: '1:496597139466:web:3da2fa62af26c01ba6dff3',
    messagingSenderId: '496597139466',
    projectId: 'slack-clone-120c3',
    authDomain: 'slack-clone-120c3.firebaseapp.com',
    storageBucket: 'slack-clone-120c3.firebasestorage.app',
    measurementId: 'G-ERCJ917N5Q',
  );
}
